version: '3.7'

services:
  mysql:
    image: mysql:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_wordpress_db_name
      MYSQL_USER: your_wordpress_db_user
      MYSQL_PASSWORD: your_wordpress_db_password

  wordpress:
    image: wordpress:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: your_wordpress_db_user
      WORDPRESS_DB_PASSWORD: your_wordpress_db_password
      WORDPRESS_DB_NAME: your_wordpress_db_name
