version: '3'

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:8080
    depends on:
      - db
    environment:
      -ALLOW_EMPTY_PASSWORD=yes
      -MARIADB_HOST=db
      -MARIADB_PORT_NUMBER=3306

db:
   image: bitnami/mariadb:latest
   environment:
      - ALLOW_EMPTY_PASSWORD=yes


  webserver:
    image: nginx
    ports:
      -80:80
      -443:443
    volumes:
         - ./certs:/etc/nginx/certs
         - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
         - drupal
